from __future__ import annotations

"""Coupled passenger-behavior and vehicle-service layers for STB-FTT.

The module implements a deliberately bounded multimodal extension of the
existing typed sparse prototype. Passenger activity columns carry person mass;
vehicle route columns carry vehicle trips and provide seat/service capacity.
The two layers are coupled by an explicit request-capacity inequality

    R x <= S y,

rather than by an implicit occupancy coefficient. Road congestion and queues
are generated by private and service vehicles, while passengers experience
travel time, waiting, transfers, price, and schedule penalties.

The implementation is a research harness, not a full fleet-dispatch system.
Shared-vehicle routes are continuous set-covering columns over aggregate
request classes, and the internal temporal backend remains a point queue
without spillback.
"""

from dataclasses import dataclass
from collections import defaultdict
import math
from typing import Iterable, Mapping, Sequence

import numpy as np
import pandas as pd
from scipy import sparse
from scipy.optimize import brentq, linprog

from tensormobility.dta.column_generation import ColumnGenerationResult, bpr_cost
from tensormobility.core.grid_network import GridCase
from tensormobility.core.network_core import StaticNetwork
from tensormobility.dynamics.path_queue import SparsePathQueueResult, run_sparse_path_point_queue
from tensormobility.core.tensor_contracts import Axis, TypedOperator, TypedVector, sparse_operator_from_triplets


# ---------------------------------------------------------------------------
# Analytical two-sided anchor
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PassengerVehicleAnalyticalResult:
    demand: float
    analytical_auto_flow: float
    analytical_shared_flow: float
    analytical_vehicle_flow: float
    analytical_service_price: float
    numerical_auto_flow: float
    numerical_shared_flow: float
    numerical_vehicle_flow: float
    numerical_service_price: float
    max_flow_error: float
    price_error: float
    iterations: int
    history: pd.DataFrame


def solve_analytical_passenger_vehicle_market(
    *,
    demand: float = 1000.0,
    auto_base_cost: float = 7.0,
    auto_congestion_slope: float = 0.006,
    shared_base_cost: float = 8.8,
    pooled_vehicle_cost: float = 7.2,
    pooled_capacity: float = 2.0,
    entropy_temperature: float = 1.4,
    damping: float = 0.55,
    tolerance: float = 1e-11,
    max_iterations: int = 500,
) -> PassengerVehicleAnalyticalResult:
    """Verify passenger choice + vehicle capacity against a scalar KKT root.

    The joint convex anchor is

        min integral c_auto(x_a) dx_a + c_s x_s + k y
            + tau * sum_m x_m(log x_m - 1)
        s.t. x_a + x_s = d,  x_s <= q y,  x,y >= 0.

    Positive vehicle cost makes the service constraint bind, so the exact
    service price is k/q and y=x_s/q. The remaining passenger KKT condition is
    a one-dimensional root solved independently with Brent's method.
    """
    if demand <= 0 or pooled_capacity <= 0 or entropy_temperature <= 0:
        raise ValueError("demand, capacity, and temperature must be positive")
    service_price = pooled_vehicle_cost / pooled_capacity

    def stationarity(auto_flow: float) -> float:
        shared_flow = demand - auto_flow
        return (
            auto_base_cost
            + auto_congestion_slope * auto_flow
            + entropy_temperature * math.log(auto_flow)
            - shared_base_cost
            - service_price
            - entropy_temperature * math.log(shared_flow)
        )

    analytical_auto = float(brentq(stationarity, 1e-10, demand - 1e-10, xtol=1e-13, rtol=1e-13))
    analytical_shared = demand - analytical_auto
    analytical_vehicle = analytical_shared / pooled_capacity

    auto = demand / 2.0
    price = 0.0
    rows: list[dict[str, float | int]] = []
    for iteration in range(1, max_iterations + 1):
        auto_cost = auto_base_cost + auto_congestion_slope * auto
        # Entropic passenger response for the current vehicle-market price.
        utility = np.asarray((-auto_cost, -(shared_base_cost + price)), dtype=float) / entropy_temperature
        utility -= utility.max()
        probability = np.exp(utility)
        probability /= probability.sum()
        target_auto = demand * float(probability[0])
        target_shared = demand - target_auto
        # The homogeneous vehicle LP has a pooled column with q seats and cost k.
        target_vehicle = target_shared / pooled_capacity
        target_price = service_price if target_shared > 1e-12 else 0.0
        residual = max(abs(target_auto - auto) / demand, abs(target_price - price) / max(service_price, 1.0))
        rows.append({
            "iteration": iteration,
            "auto_flow": auto,
            "shared_flow": demand - auto,
            "vehicle_flow": (demand - auto) / pooled_capacity,
            "service_price": price,
            "fixed_point_residual": residual,
        })
        auto = (1.0 - damping) * auto + damping * target_auto
        price = (1.0 - damping) * price + damping * target_price
        if residual <= tolerance:
            break

    numerical_shared = demand - auto
    numerical_vehicle = numerical_shared / pooled_capacity
    return PassengerVehicleAnalyticalResult(
        demand=float(demand),
        analytical_auto_flow=analytical_auto,
        analytical_shared_flow=analytical_shared,
        analytical_vehicle_flow=analytical_vehicle,
        analytical_service_price=service_price,
        numerical_auto_flow=float(auto),
        numerical_shared_flow=float(numerical_shared),
        numerical_vehicle_flow=float(numerical_vehicle),
        numerical_service_price=float(price),
        max_flow_error=float(max(abs(auto - analytical_auto), abs(numerical_shared - analytical_shared))),
        price_error=float(abs(price - service_price)),
        iterations=len(rows),
        history=pd.DataFrame(rows),
    )


# ---------------------------------------------------------------------------
# Vehicle route-column generation
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VehiclePattern:
    pattern_id: str
    service_mode: str
    departure_index: int
    pattern_type: str
    served_request_indices: tuple[int, ...]
    served_capacities: tuple[float, ...]
    link_sequence: tuple[int, ...]
    operating_cost: float
    free_flow_time: float


@dataclass(frozen=True)
class VehicleColumnGenerationResult:
    request_table: pd.DataFrame
    pattern_table: pd.DataFrame
    request_dual_price: pd.Series
    average_service_price: pd.Series
    road_link_flow: np.ndarray
    supplied_capacity: np.ndarray
    demand_residual: float
    relative_pricing_gap: float
    iterations: int
    pricing_calls: int
    history: pd.DataFrame


def _path_cost(path: Sequence[int], link_cost: np.ndarray) -> float:
    return float(link_cost[np.asarray(path, dtype=int)].sum()) if path else 0.0


def _concat_paths(*segments: Sequence[int]) -> tuple[int, ...]:
    out: list[int] = []
    for segment in segments:
        out.extend(int(v) for v in segment)
    return tuple(out)


def _node_xy(network: StaticNetwork) -> dict[int, tuple[float, float]]:
    x = network.nodes.get("x_coord", pd.Series(np.arange(network.n_nodes))).to_numpy(float)
    y = network.nodes.get("y_coord", pd.Series(np.zeros(network.n_nodes))).to_numpy(float)
    return {int(node): (float(xx), float(yy)) for node, xx, yy in zip(network.nodes["node_id"], x, y, strict=True)}


def _manhattan(xy: Mapping[int, tuple[float, float]], a: int, b: int) -> float:
    xa, ya = xy[int(a)]
    xb, yb = xy[int(b)]
    return abs(xa - xb) + abs(ya - yb)


def _best_pooled_route(
    network: StaticNetwork,
    request_a: pd.Series,
    request_b: pd.Series,
    link_cost: np.ndarray,
) -> tuple[tuple[int, ...], float]:
    """Return the least-cost pickup-before-dropoff order for two requests."""
    oa, da = int(request_a.origin_node_id), int(request_a.destination_node_id)
    ob, db = int(request_b.origin_node_id), int(request_b.destination_node_id)
    node_orders = (
        (oa, ob, da, db),
        (oa, ob, db, da),
        (ob, oa, da, db),
        (ob, oa, db, da),
    )
    best_path: tuple[int, ...] | None = None
    best_cost = np.inf
    for order in node_orders:
        segments: list[tuple[int, ...]] = []
        total = 0.0
        feasible = True
        for u, v in zip(order[:-1], order[1:], strict=True):
            if u == v:
                segments.append(tuple())
                continue
            try:
                path, cost = network.shortest_path(u, v, link_cost)
            except RuntimeError:
                feasible = False
                break
            segments.append(path)
            total += cost
        if feasible and total < best_cost:
            best_cost = float(total)
            best_path = _concat_paths(*segments)
    if best_path is None:
        raise RuntimeError("no feasible pooled route")
    return best_path, best_cost


def _build_vehicle_pattern_pool(
    network: StaticNetwork,
    request_table: pd.DataFrame,
    link_cost: np.ndarray,
    *,
    shared_capacity: float,
    bus_capacity: float,
    pickup_overhead: float,
    pooled_overhead: float,
    bus_dispatch_cost: float,
    max_pair_distance: float,
    pair_neighbours: int,
) -> tuple[list[VehiclePattern], list[VehiclePattern]]:
    """Build mandatory initial columns and compatible pooled candidates."""
    requests = request_table.reset_index(drop=True)
    xy = _node_xy(network)
    initial: list[VehiclePattern] = []
    candidates: list[VehiclePattern] = []

    shared_indices = requests.index[requests["service_mode"] == "shared_ride"].tolist()
    for r in shared_indices:
        row = requests.iloc[r]
        path, travel_time = network.shortest_path(int(row.origin_node_id), int(row.destination_node_id), link_cost)
        initial.append(VehiclePattern(
            pattern_id=f"shared_direct:{row.request_id}",
            service_mode="shared_ride",
            departure_index=int(row.departure_index),
            pattern_type="direct",
            served_request_indices=(int(r),),
            served_capacities=(1.0,),
            link_sequence=path,
            operating_cost=float(travel_time + pickup_overhead),
            free_flow_time=float(_path_cost(path, network.free_flow_time)),
        ))
        candidates.append(VehiclePattern(
            pattern_id=f"shared_same_pool:{row.request_id}",
            service_mode="shared_ride",
            departure_index=int(row.departure_index),
            pattern_type="same_request_pool",
            served_request_indices=(int(r),),
            served_capacities=(float(shared_capacity),),
            link_sequence=path,
            operating_cost=float(1.8 * travel_time + pooled_overhead),
            free_flow_time=float(_path_cost(path, network.free_flow_time)),
        ))

    # Bus request rows contain the full directional service path as a semicolon
    # separated link-index sequence. One bus-run column provides many seats.
    for r in requests.index[requests["service_mode"] == "bus"].tolist():
        row = requests.iloc[r]
        text = str(row.link_index_sequence)
        path = tuple(int(v) for v in text.split(";") if str(v).strip())
        initial.append(VehiclePattern(
            pattern_id=f"bus_run:{row.request_id}",
            service_mode="bus",
            departure_index=int(row.departure_index),
            pattern_type="scheduled_run",
            served_request_indices=(int(r),),
            served_capacities=(float(bus_capacity),),
            link_sequence=path,
            operating_cost=float(_path_cost(path, link_cost) + bus_dispatch_cost),
            free_flow_time=float(_path_cost(path, network.free_flow_time)),
        ))

    # Spatially and temporally compatible shared request classes form pooled
    # candidate columns. Neighbour filtering avoids an O(R^2) route explosion.
    for r in shared_indices:
        row_r = requests.iloc[r]
        alternatives: list[tuple[float, int]] = []
        for s in shared_indices:
            if s <= r:
                continue
            row_s = requests.iloc[s]
            if int(row_s.departure_index) != int(row_r.departure_index):
                continue
            distance = _manhattan(xy, int(row_r.origin_node_id), int(row_s.origin_node_id)) + _manhattan(
                xy, int(row_r.destination_node_id), int(row_s.destination_node_id)
            )
            if distance <= max_pair_distance:
                alternatives.append((distance, int(s)))
        alternatives.sort()
        for _, s in alternatives[:pair_neighbours]:
            row_s = requests.iloc[s]
            path, travel_time = _best_pooled_route(network, row_r, row_s, link_cost)
            candidates.append(VehiclePattern(
                pattern_id=f"shared_pair:{row_r.request_id}|{row_s.request_id}",
                service_mode="shared_ride",
                departure_index=int(row_r.departure_index),
                pattern_type="paired_requests",
                served_request_indices=(int(r), int(s)),
                served_capacities=(1.0, 1.0),
                link_sequence=path,
                operating_cost=float(travel_time + pooled_overhead),
                free_flow_time=float(_path_cost(path, network.free_flow_time)),
            ))
    return initial, candidates


def _solve_vehicle_master(
    patterns: Sequence[VehiclePattern],
    demand: np.ndarray,
    n_requests: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    if not patterns:
        if np.max(demand, initial=0.0) > 1e-12:
            raise RuntimeError("vehicle master has demand but no columns")
        return np.zeros(0), np.zeros(n_requests), np.zeros(n_requests), 0.0
    rows: list[int] = []
    cols: list[int] = []
    data: list[float] = []
    cost = np.zeros(len(patterns), dtype=float)
    for j, pattern in enumerate(patterns):
        cost[j] = pattern.operating_cost
        for r, capacity in zip(pattern.served_request_indices, pattern.served_capacities, strict=True):
            rows.append(int(r))
            cols.append(j)
            data.append(float(capacity))
    coverage = sparse.coo_matrix((data, (rows, cols)), shape=(n_requests, len(patterns))).tocsr()
    result = linprog(
        c=cost,
        A_ub=-coverage,
        b_ub=-demand,
        bounds=(0.0, None),
        method="highs",
    )
    if not result.success:
        raise RuntimeError(f"vehicle restricted master failed: {result.message}")
    y = np.asarray(result.x, dtype=float)
    supplied = np.asarray(coverage @ y).ravel()
    # For -Qy <= -d, HiGHS marginals are non-positive; negate them to
    # obtain nonnegative marginal service prices.
    dual = -np.asarray(result.ineqlin.marginals, dtype=float)
    residual = float(np.max(np.maximum(demand - supplied, 0.0), initial=0.0))
    return y, supplied, dual, residual


def solve_vehicle_service_column_generation(
    network: StaticNetwork,
    request_table: pd.DataFrame,
    link_cost: np.ndarray,
    *,
    shared_capacity: float = 2.0,
    bus_capacity: float = 40.0,
    pickup_overhead: float = 1.4,
    pooled_overhead: float = 2.0,
    bus_dispatch_cost: float = 8.0,
    max_pair_distance: float = 5.0,
    pair_neighbours: int = 5,
    max_iterations: int = 20,
    pricing_tolerance: float = 1e-8,
    add_per_iteration: int = 20,
) -> VehicleColumnGenerationResult:
    required = {
        "request_id",
        "service_mode",
        "departure_index",
        "origin_node_id",
        "destination_node_id",
        "demand",
        "link_index_sequence",
    }
    missing = required - set(request_table.columns)
    if missing:
        raise ValueError(f"request_table missing fields {missing}")
    requests = request_table.copy().reset_index(drop=True)
    demand = requests["demand"].to_numpy(float)
    if np.any(demand < -1e-10) or np.any(~np.isfinite(demand)):
        raise ValueError("service demand must be finite and nonnegative")
    costs = np.asarray(link_cost, dtype=float)
    if costs.shape != (network.n_links,):
        raise ValueError("link_cost has wrong shape")

    initial, candidates = _build_vehicle_pattern_pool(
        network,
        requests,
        costs,
        shared_capacity=shared_capacity,
        bus_capacity=bus_capacity,
        pickup_overhead=pickup_overhead,
        pooled_overhead=pooled_overhead,
        bus_dispatch_cost=bus_dispatch_cost,
        max_pair_distance=max_pair_distance,
        pair_neighbours=pair_neighbours,
    )
    active = list(initial)
    active_ids = {pattern.pattern_id for pattern in active}
    rows: list[dict[str, float | int]] = []
    pricing_calls = 0
    min_reduced_cost = 0.0

    for iteration in range(1, max_iterations + 1):
        y, supplied, dual, residual = _solve_vehicle_master(active, demand, len(requests))
        priced: list[tuple[float, VehiclePattern]] = []
        for pattern in candidates:
            if pattern.pattern_id in active_ids:
                continue
            pricing_calls += 1
            value = sum(
                float(capacity) * float(dual[int(r)])
                for r, capacity in zip(pattern.served_request_indices, pattern.served_capacities, strict=True)
            )
            reduced_cost = float(pattern.operating_cost - value)
            if reduced_cost < -pricing_tolerance:
                priced.append((reduced_cost, pattern))
        priced.sort(key=lambda item: item[0])
        min_reduced_cost = float(priced[0][0]) if priced else 0.0
        rows.append({
            "iteration": iteration,
            "active_patterns": len(active),
            "positive_pattern_flows": int(np.count_nonzero(y > 1e-9)),
            "objective": float(sum(p.operating_cost * yy for p, yy in zip(active, y, strict=True))),
            "max_service_shortfall": residual,
            "minimum_candidate_reduced_cost": min_reduced_cost,
            "columns_added": min(len(priced), add_per_iteration),
        })
        if not priced:
            break
        for _, pattern in priced[:add_per_iteration]:
            active.append(pattern)
            active_ids.add(pattern.pattern_id)

    y, supplied, dual, residual = _solve_vehicle_master(active, demand, len(requests))
    road_flow = np.zeros(network.n_links, dtype=float)
    pattern_rows: list[dict[str, object]] = []
    for pattern, flow in zip(active, y, strict=True):
        if flow > 0 and pattern.link_sequence:
            road_flow[np.asarray(pattern.link_sequence, dtype=int)] += float(flow)
        pattern_rows.append({
            "pattern_id": pattern.pattern_id,
            "service_mode": pattern.service_mode,
            "departure_index": pattern.departure_index,
            "pattern_type": pattern.pattern_type,
            "served_request_indices": ";".join(map(str, pattern.served_request_indices)),
            "served_request_ids": ";".join(str(requests.iloc[r].request_id) for r in pattern.served_request_indices),
            "served_capacities": ";".join(f"{v:.8g}" for v in pattern.served_capacities),
            "vehicle_flow": float(flow),
            "operating_cost": pattern.operating_cost,
            "free_flow_time": pattern.free_flow_time,
            "link_index_sequence": ";".join(map(str, pattern.link_sequence)),
            "n_links": len(pattern.link_sequence),
        })
    pattern_table = pd.DataFrame(pattern_rows)
    average_numerator = np.zeros(len(requests), dtype=float)
    average_denominator = np.zeros(len(requests), dtype=float)
    for pattern, flow in zip(active, y, strict=True):
        if flow <= 0:
            continue
        total_capacity = max(float(sum(pattern.served_capacities)), 1e-12)
        unit_cost = float(pattern.operating_cost) / total_capacity
        for r, capacity in zip(pattern.served_request_indices, pattern.served_capacities, strict=True):
            served = float(flow) * float(capacity)
            average_numerator[int(r)] += served * unit_cost
            average_denominator[int(r)] += served
    average_price = np.divide(
        average_numerator,
        average_denominator,
        out=dual.copy(),
        where=average_denominator > 1e-12,
    )
    scale = max(float(np.dot(dual, demand)), 1.0)
    relative_gap = max(-min_reduced_cost, 0.0) / scale
    return VehicleColumnGenerationResult(
        request_table=requests,
        pattern_table=pattern_table,
        request_dual_price=pd.Series(dual, index=requests["request_id"].astype(str), name="service_dual_price"),
        average_service_price=pd.Series(average_price, index=requests["request_id"].astype(str), name="average_service_price"),
        road_link_flow=road_flow,
        supplied_capacity=supplied,
        demand_residual=residual,
        relative_pricing_gap=float(relative_gap),
        iterations=len(rows),
        pricing_calls=pricing_calls,
        history=pd.DataFrame(rows),
    )


# ---------------------------------------------------------------------------
# Passenger activity / multimodal columns
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PassengerBehaviorParameters:
    logit_temperature: float = 2.0
    walk_minutes_per_grid_link: float = 4.0
    shared_wait_minutes: float = 5.0
    bus_wait_minutes: float = 6.0
    bus_in_vehicle_factor: float = 1.15
    shared_detour_factor: float = 1.08
    parking_penalty: float = 2.5
    transfer_penalty: float = 2.0
    auto_monetary_cost: float = 2.0
    shared_monetary_cost: float = 1.5
    bus_monetary_cost: float = 0.8
    park_ride_monetary_cost: float = 1.2
    schedule_penalty_mandatory: float = 1.5
    schedule_penalty_discretionary: float = 0.6


@dataclass(frozen=True)
class PassengerVehicleModel:
    case: GridCase
    groups: pd.DataFrame
    columns: pd.DataFrame
    group_axis: Axis
    column_axis: Axis
    request_axis: Axis
    column_to_request: TypedOperator
    group_columns: tuple[np.ndarray, ...]
    request_template: pd.DataFrame
    bus_line_paths: dict[str, tuple[int, ...]]
    n_departures: int

    @property
    def demands(self) -> np.ndarray:
        return self.groups["demand"].to_numpy(float)


@dataclass(frozen=True)
class PassengerChoiceResult:
    column_table: pd.DataFrame
    service_request_table: pd.DataFrame
    private_vehicle_path_departure: dict[tuple[tuple[int, ...], int], float]
    mode_share: pd.DataFrame
    departure_share: pd.DataFrame
    activity_mode_share: pd.DataFrame
    mass_residual: float
    total_person_demand: float
    total_private_vehicle_trips: float


@dataclass(frozen=True)
class ModeInteractionResult:
    """Local connected-choice response under fixed network and service supply.

    A positive generalized-cost perturbation is applied to one mode at a time.
    The resulting share derivative separates the direct behavioral substitution
    graph from the slower vehicle-supply and congestion feedback loops.
    """

    long_table: pd.DataFrame
    derivative_matrix: pd.DataFrame
    delta_cost: float
    max_row_sum_residual: float


def _parse_path(value: object) -> tuple[int, ...]:
    if isinstance(value, tuple):
        return tuple(int(v) for v in value)
    if isinstance(value, list):
        return tuple(int(v) for v in value)
    text = str(value).strip()
    return tuple(int(v) for v in text.split(";") if str(v).strip()) if text else tuple()


def _select_od_routes(assignment: ColumnGenerationResult, max_paths: int) -> dict[str, list[tuple[int, ...]]]:
    routes: dict[str, list[tuple[int, ...]]] = {}
    table = assignment.path_table.copy()
    if table.empty:
        return routes
    table = table.sort_values(["od_id", "path_flow", "path_cost"], ascending=[True, False, True])
    for od_id, group in table.groupby("od_id", sort=False):
        unique: list[tuple[int, ...]] = []
        for value in group["link_index_sequence"]:
            path = _parse_path(value)
            if path and path not in unique:
                unique.append(path)
            if len(unique) >= max_paths:
                break
        routes[str(od_id)] = unique
    return routes


def _grid_bus_line(case: GridCase) -> tuple[dict[int, int], dict[str, tuple[int, ...]], tuple[int, ...]]:
    row = case.rows // 2
    stop_by_column = {c: row * case.columns + c + 1 for c in range(case.columns)}
    east_nodes = tuple(stop_by_column[c] for c in range(case.columns))
    west_nodes = tuple(reversed(east_nodes))
    east_links: list[int] = []
    west_links: list[int] = []
    for nodes, target in ((east_nodes, east_links), (west_nodes, west_links)):
        for u, v in zip(nodes[:-1], nodes[1:], strict=True):
            path, _ = case.network.shortest_path(u, v, case.network.free_flow_time)
            target.extend(path)
    return stop_by_column, {"E": tuple(east_links), "W": tuple(west_links)}, east_nodes


def build_passenger_vehicle_model(
    case: GridCase,
    assignment: ColumnGenerationResult,
    *,
    n_departures: int = 4,
    traveler_classes: tuple[str, ...] = ("commuter", "flexible"),
    class_shares: tuple[float, ...] = (0.65, 0.35),
    activities: tuple[str, ...] = ("mandatory", "discretionary"),
    activity_shares: tuple[float, ...] = (0.70, 0.30),
    max_auto_paths: int = 2,
) -> PassengerVehicleModel:
    if n_departures < 2:
        raise ValueError("n_departures must be at least two")
    if len(traveler_classes) != len(class_shares) or not np.isclose(sum(class_shares), 1.0):
        raise ValueError("traveler class shares are invalid")
    if len(activities) != len(activity_shares) or not np.isclose(sum(activity_shares), 1.0):
        raise ValueError("activity shares are invalid")

    routes_by_od = _select_od_routes(assignment, max_auto_paths)
    stop_by_column, bus_paths, _ = _grid_bus_line(case)
    xy = _node_xy(case.network)

    group_rows: list[dict[str, object]] = []
    for od in case.demand.itertuples(index=False):
        for class_index, (traveler_class, class_share) in enumerate(zip(traveler_classes, class_shares, strict=True)):
            for activity_index, (activity, activity_share) in enumerate(zip(activities, activity_shares, strict=True)):
                group_rows.append({
                    "group_index": len(group_rows),
                    "group_id": f"{od.od_id}:{traveler_class}:{activity}",
                    "od_id": str(od.od_id),
                    "origin_node_id": int(od.origin_node_id),
                    "destination_node_id": int(od.destination_node_id),
                    "traveler_class": traveler_class,
                    "class_index": class_index,
                    "activity": activity,
                    "activity_index": activity_index,
                    "demand": float(od.volume) * float(class_share) * float(activity_share),
                    "preferred_departure": int(round((n_departures - 1) * (0.35 if activity == "mandatory" else 0.65))),
                    "value_of_time": 1.25 if traveler_class == "commuter" else 0.90,
                })
    groups = pd.DataFrame(group_rows)

    request_rows: dict[str, dict[str, object]] = {}
    column_rows: list[dict[str, object]] = []
    for group in group_rows:
        od_id = str(group["od_id"])
        origin = int(group["origin_node_id"])
        destination = int(group["destination_node_id"])
        auto_routes = routes_by_od.get(od_id)
        if not auto_routes:
            path, _ = case.network.shortest_path(origin, destination, case.network.free_flow_time)
            auto_routes = [path]
        shared_path = auto_routes[0]
        o_col = int(round(xy[origin][0]))
        d_col = int(round(xy[destination][0]))
        o_stop = int(stop_by_column[min(max(o_col, 0), case.columns - 1)])
        d_stop = int(stop_by_column[min(max(d_col, 0), case.columns - 1)])
        bus_valid = o_stop != d_stop
        direction = "E" if d_col > o_col else "W"
        bus_path = bus_paths[direction]
        # Passenger rides only the line segment between the nearest stops.
        bus_segment, _ = case.network.shortest_path(o_stop, d_stop, case.network.free_flow_time) if bus_valid else (tuple(), 0.0)
        access_walk_links = _manhattan(xy, origin, o_stop)
        egress_walk_links = _manhattan(xy, d_stop, destination)
        park_access_path, _ = case.network.shortest_path(origin, o_stop, case.network.free_flow_time) if origin != o_stop else (tuple(), 0.0)

        for departure in range(n_departures):
            # Private auto route alternatives.
            for route_rank, path in enumerate(auto_routes):
                column_rows.append({
                    "column_index": len(column_rows),
                    "column_id": f"{group['group_id']}:auto:t{departure}:r{route_rank}",
                    "group_index": int(group["group_index"]),
                    "od_id": od_id,
                    "mode": "drive_alone",
                    "departure_index": departure,
                    "route_rank": route_rank,
                    "road_path": path,
                    "private_vehicle_path": path,
                    "bus_segment_path": tuple(),
                    "shared_request_id": "",
                    "bus_request_id": "",
                    "access_walk_links": 0.0,
                    "egress_walk_links": 0.0,
                    "base_constant": 0.0,
                })
            shared_request = f"shared:{od_id}:t{departure}"
            request_rows.setdefault(shared_request, {
                "request_id": shared_request,
                "service_mode": "shared_ride",
                "departure_index": departure,
                "origin_node_id": origin,
                "destination_node_id": destination,
                "demand": 0.0,
                "link_index_sequence": "",
            })
            column_rows.append({
                "column_index": len(column_rows),
                "column_id": f"{group['group_id']}:shared:t{departure}",
                "group_index": int(group["group_index"]),
                "od_id": od_id,
                "mode": "shared_ride",
                "departure_index": departure,
                "route_rank": 0,
                "road_path": shared_path,
                "private_vehicle_path": tuple(),
                "bus_segment_path": tuple(),
                "shared_request_id": shared_request,
                "bus_request_id": "",
                "access_walk_links": 0.0,
                "egress_walk_links": 0.0,
                "base_constant": 0.8,
            })
            if bus_valid:
                bus_request = f"bus:{direction}:t{departure}"
                request_rows.setdefault(bus_request, {
                    "request_id": bus_request,
                    "service_mode": "bus",
                    "departure_index": departure,
                    "origin_node_id": int(bus_paths[direction] and case.network.links.iloc[bus_paths[direction][0]].from_node_id or o_stop),
                    "destination_node_id": int(bus_paths[direction] and case.network.links.iloc[bus_paths[direction][-1]].to_node_id or d_stop),
                    "demand": 0.0,
                    "link_index_sequence": ";".join(map(str, bus_path)),
                })
                column_rows.append({
                    "column_index": len(column_rows),
                    "column_id": f"{group['group_id']}:bus:t{departure}",
                    "group_index": int(group["group_index"]),
                    "od_id": od_id,
                    "mode": "bus",
                    "departure_index": departure,
                    "route_rank": 0,
                    "road_path": bus_segment,
                    "private_vehicle_path": tuple(),
                    "bus_segment_path": bus_segment,
                    "shared_request_id": "",
                    "bus_request_id": bus_request,
                    "access_walk_links": access_walk_links,
                    "egress_walk_links": egress_walk_links,
                    "base_constant": 1.5,
                })
                column_rows.append({
                    "column_index": len(column_rows),
                    "column_id": f"{group['group_id']}:park_ride:t{departure}",
                    "group_index": int(group["group_index"]),
                    "od_id": od_id,
                    "mode": "park_ride",
                    "departure_index": departure,
                    "route_rank": 0,
                    "road_path": _concat_paths(park_access_path, bus_segment),
                    "private_vehicle_path": park_access_path,
                    "bus_segment_path": bus_segment,
                    "shared_request_id": "",
                    "bus_request_id": bus_request,
                    "access_walk_links": 0.0,
                    "egress_walk_links": egress_walk_links,
                    "base_constant": 1.0,
                })

    columns = pd.DataFrame(column_rows)
    requests = pd.DataFrame(list(request_rows.values())).sort_values("request_id").reset_index(drop=True)
    request_index = {str(v): i for i, v in enumerate(requests["request_id"])}
    rows: list[int] = []
    cols: list[int] = []
    values: list[float] = []
    for column in columns.itertuples(index=False):
        request_id = str(column.shared_request_id or column.bus_request_id)
        if request_id:
            rows.append(request_index[request_id])
            cols.append(int(column.column_index))
            values.append(1.0)

    group_axis = Axis("passenger_group", tuple(groups["group_id"].astype(str)), "OD x traveler class x activity")
    column_axis = Axis("passenger_behavioral_column", tuple(columns["column_id"].astype(str)), "mode x departure x route")
    request_axis = Axis("mobility_service_request", tuple(requests["request_id"].astype(str)), "shared request and bus-seat resources")
    column_to_request = sparse_operator_from_triplets(
        name="passenger_column_to_service_request",
        source=column_axis,
        target=request_axis,
        rows=rows,
        cols=cols,
        values=values,
        input_measure="person_flow",
        output_measure="person_flow",
        conservation="none",
        description="Maps passenger columns to service-seat demand; private modes map to no service request.",
    )
    group_index_values = columns["group_index"].to_numpy(int)
    group_columns = tuple(np.flatnonzero(group_index_values == g) for g in range(len(groups)))
    return PassengerVehicleModel(
        case=case,
        groups=groups,
        columns=columns,
        group_axis=group_axis,
        column_axis=column_axis,
        request_axis=request_axis,
        column_to_request=column_to_request,
        group_columns=group_columns,
        request_template=requests,
        bus_line_paths=bus_paths,
        n_departures=n_departures,
    )


def _dynamic_path_time(
    path: tuple[int, ...],
    departure: int,
    link_cost: np.ndarray,
    override: Mapping[tuple[tuple[int, ...], int], float] | None,
) -> float:
    if override is not None:
        value = override.get((path, int(departure)))
        if value is not None and np.isfinite(value):
            return float(value)
    return _path_cost(path, link_cost)


def evaluate_passenger_choice(
    model: PassengerVehicleModel,
    link_cost: np.ndarray,
    service_price: Mapping[str, float] | pd.Series | None = None,
    *,
    parameters: PassengerBehaviorParameters = PassengerBehaviorParameters(),
    dynamic_time_override: Mapping[tuple[tuple[int, ...], int], float] | None = None,
    mode_cost_adjustment: Mapping[str, float] | None = None,
) -> PassengerChoiceResult:
    costs = np.asarray(link_cost, dtype=float)
    if costs.shape != (model.case.network.n_links,):
        raise ValueError("link_cost has wrong shape")
    price = {} if service_price is None else {str(k): float(v) for k, v in dict(service_price).items()}
    mode_adjustment = {} if mode_cost_adjustment is None else {str(k): float(v) for k, v in dict(mode_cost_adjustment).items()}
    columns = model.columns.copy()
    group_lookup = model.groups.set_index("group_index")
    generalized_cost = np.zeros(len(columns), dtype=float)

    for row in columns.itertuples(index=False):
        group = group_lookup.loc[int(row.group_index)]
        departure = int(row.departure_index)
        vot = float(group.value_of_time)
        preferred = int(group.preferred_departure)
        schedule_weight = (
            parameters.schedule_penalty_mandatory
            if str(group.activity) == "mandatory"
            else parameters.schedule_penalty_discretionary
        )
        schedule = schedule_weight * abs(departure - preferred)
        mode = str(row.mode)
        road_path = tuple(row.road_path)
        if mode == "drive_alone":
            travel = _dynamic_path_time(road_path, departure, costs, dynamic_time_override)
            monetary = parameters.auto_monetary_cost
            wait_transfer = 0.0
            service = 0.0
        elif mode == "shared_ride":
            travel = parameters.shared_detour_factor * _dynamic_path_time(road_path, departure, costs, dynamic_time_override)
            monetary = parameters.shared_monetary_cost
            wait_transfer = parameters.shared_wait_minutes
            service = price.get(str(row.shared_request_id), 0.0)
        elif mode == "bus":
            bus_time = _dynamic_path_time(tuple(row.bus_segment_path), departure, costs, dynamic_time_override)
            travel = (
                parameters.walk_minutes_per_grid_link * (float(row.access_walk_links) + float(row.egress_walk_links))
                + parameters.bus_in_vehicle_factor * bus_time
            )
            monetary = parameters.bus_monetary_cost
            wait_transfer = parameters.bus_wait_minutes + parameters.transfer_penalty
            service = price.get(str(row.bus_request_id), 0.0)
        elif mode == "park_ride":
            access = _dynamic_path_time(tuple(row.private_vehicle_path), departure, costs, dynamic_time_override)
            bus_time = _dynamic_path_time(tuple(row.bus_segment_path), departure, costs, dynamic_time_override)
            travel = access + parameters.bus_in_vehicle_factor * bus_time + parameters.walk_minutes_per_grid_link * float(row.egress_walk_links)
            monetary = parameters.park_ride_monetary_cost + parameters.parking_penalty
            wait_transfer = parameters.bus_wait_minutes + parameters.transfer_penalty
            service = price.get(str(row.bus_request_id), 0.0)
        else:
            raise ValueError(f"unknown mode {mode}")
        generalized_cost[int(row.column_index)] = (
            float(row.base_constant)
            + vot * travel
            + monetary
            + wait_transfer
            + service
            + schedule
            + mode_adjustment.get(mode, 0.0)
        )

    probability = np.zeros(len(columns), dtype=float)
    person_flow = np.zeros(len(columns), dtype=float)
    demands = model.demands
    for group_index, indices in enumerate(model.group_columns):
        group_cost = generalized_cost[indices]
        shifted = -(group_cost - group_cost.min()) / parameters.logit_temperature
        expv = np.exp(np.clip(shifted, -700.0, 0.0))
        prob = expv / expv.sum()
        probability[indices] = prob
        person_flow[indices] = demands[group_index] * prob

    column_vector = TypedVector(model.column_axis, person_flow, "person_flow", "persons", "passenger_column_flow")
    request_vector = model.column_to_request.apply(column_vector, output_name="service_request_demand", unit="persons")
    request_table = model.request_template.copy()
    request_table["demand"] = request_vector.values

    private_flows: defaultdict[tuple[tuple[int, ...], int], float] = defaultdict(float)
    for row, flow in zip(columns.itertuples(index=False), person_flow, strict=True):
        path = tuple(row.private_vehicle_path)
        if path and flow > 0:
            private_flows[(path, int(row.departure_index))] += float(flow)

    result_table = columns.copy()
    result_table["generalized_cost"] = generalized_cost
    result_table["probability"] = probability
    result_table["person_flow"] = person_flow
    result_table = result_table.merge(
        model.groups[["group_index", "traveler_class", "activity", "demand"]], on="group_index", how="left"
    )
    total = float(person_flow.sum())
    mode = result_table.groupby("mode", as_index=False)["person_flow"].sum()
    mode["share"] = mode["person_flow"] / max(total, 1.0)
    departure = result_table.groupby("departure_index", as_index=False)["person_flow"].sum()
    departure["share"] = departure["person_flow"] / max(total, 1.0)
    activity_mode = result_table.groupby(["activity", "mode"], as_index=False)["person_flow"].sum()
    activity_totals = activity_mode.groupby("activity")["person_flow"].transform("sum")
    activity_mode["share_within_activity"] = activity_mode["person_flow"] / np.maximum(activity_totals, 1e-12)
    group_sum = result_table.groupby("group_index")["person_flow"].sum().reindex(range(len(model.groups)), fill_value=0.0).to_numpy()
    mass_residual = float(np.max(np.abs(group_sum - demands), initial=0.0))
    return PassengerChoiceResult(
        column_table=result_table,
        service_request_table=request_table,
        private_vehicle_path_departure=dict(private_flows),
        mode_share=mode,
        departure_share=departure,
        activity_mode_share=activity_mode,
        mass_residual=mass_residual,
        total_person_demand=total,
        total_private_vehicle_trips=float(sum(private_flows.values())),
    )


def compute_mode_interaction_matrix(
    model: PassengerVehicleModel,
    link_cost: np.ndarray,
    service_price: Mapping[str, float] | pd.Series | None = None,
    *,
    parameters: PassengerBehaviorParameters = PassengerBehaviorParameters(),
    delta_cost: float = 0.25,
) -> ModeInteractionResult:
    """Compute the local connected transportation choice graph.

    The network and vehicle service prices are frozen so the matrix measures
    direct behavioral substitution. Each row perturbs one mode's generalized
    cost; each column reports the derivative of another mode's passenger share.
    Rows should sum to zero because total passenger mass is conserved.
    """
    if delta_cost <= 0:
        raise ValueError("delta_cost must be positive")
    base = evaluate_passenger_choice(
        model, link_cost, service_price, parameters=parameters
    )
    modes = tuple(sorted(base.mode_share["mode"].astype(str)))
    base_share = base.mode_share.set_index("mode")["share"].reindex(modes).astype(float)
    rows: list[dict[str, float | str]] = []
    for perturbed_mode in modes:
        perturbed = evaluate_passenger_choice(
            model,
            link_cost,
            service_price,
            parameters=parameters,
            mode_cost_adjustment={perturbed_mode: delta_cost},
        )
        perturbed_share = perturbed.mode_share.set_index("mode")["share"].reindex(modes).astype(float)
        derivative = (perturbed_share - base_share) / delta_cost
        for response_mode in modes:
            rows.append({
                "perturbed_mode": perturbed_mode,
                "response_mode": response_mode,
                "base_share": float(base_share.loc[response_mode]),
                "perturbed_share": float(perturbed_share.loc[response_mode]),
                "share_derivative_per_cost": float(derivative.loc[response_mode]),
            })
    long_table = pd.DataFrame(rows)
    matrix = long_table.pivot(
        index="perturbed_mode", columns="response_mode", values="share_derivative_per_cost"
    ).reindex(index=modes, columns=modes)
    row_sum_residual = float(np.max(np.abs(matrix.sum(axis=1).to_numpy(float)), initial=0.0))
    return ModeInteractionResult(
        long_table=long_table,
        derivative_matrix=matrix,
        delta_cost=float(delta_cost),
        max_row_sum_residual=row_sum_residual,
    )


# ---------------------------------------------------------------------------
# Coupled multimodal passenger-vehicle solve
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PassengerVehicleEquilibriumResult:
    model: PassengerVehicleModel
    passenger: PassengerChoiceResult
    vehicle: VehicleColumnGenerationResult
    road_link_vehicle_flow: np.ndarray
    link_cost: np.ndarray
    queue: SparsePathQueueResult
    fixed_point_residual: float
    iterations: int
    history: pd.DataFrame
    dynamic_path_time: dict[tuple[tuple[int, ...], int], float]


def _private_link_flow(network: StaticNetwork, flows: Mapping[tuple[tuple[int, ...], int], float]) -> np.ndarray:
    link = np.zeros(network.n_links, dtype=float)
    for (path, _), amount in flows.items():
        if path and amount > 0:
            link[np.asarray(path, dtype=int)] += float(amount)
    return link


def _aggregate_dynamic_paths(
    model: PassengerVehicleModel,
    passenger: PassengerChoiceResult,
    vehicle: VehicleColumnGenerationResult,
) -> tuple[list[tuple[int, ...]], np.ndarray]:
    flow: defaultdict[tuple[tuple[int, ...], int], float] = defaultdict(float)
    for key, amount in passenger.private_vehicle_path_departure.items():
        flow[key] += float(amount)
    for row in vehicle.pattern_table.itertuples(index=False):
        amount = float(row.vehicle_flow)
        path = _parse_path(row.link_index_sequence)
        if amount > 0 and path:
            flow[(path, int(row.departure_index))] += amount
    paths = sorted({path for path, _ in flow}, key=lambda p: (len(p), p))
    path_index = {path: i for i, path in enumerate(paths)}
    departures = np.zeros((len(paths), model.n_departures), dtype=float)
    for (path, departure), amount in flow.items():
        if 0 <= departure < model.n_departures:
            departures[path_index[path], departure] += float(amount)
    return paths, departures


def _queue_time_map(
    paths: Sequence[tuple[int, ...]],
    queue: SparsePathQueueResult,
) -> dict[tuple[tuple[int, ...], int], float]:
    result: dict[tuple[tuple[int, ...], int], float] = {}
    for p, path in enumerate(paths):
        for t in range(queue.path_departure_travel_time.shape[1]):
            result[(tuple(path), t)] = float(queue.path_departure_travel_time[p, t])
    return result


def solve_passenger_vehicle_equilibrium(
    model: PassengerVehicleModel,
    *,
    parameters: PassengerBehaviorParameters = PassengerBehaviorParameters(),
    max_iterations: int = 35,
    damping: float = 0.45,
    tolerance: float = 2e-3,
    dynamic_feedback: bool = True,
    queue_every: int = 3,
    queue_horizon_steps: int = 120,
    dynamic_damping: float = 0.08,
    capacity_multiplier: np.ndarray | float = 1.0,
    vehicle_solver_options: Mapping[str, object] | None = None,
    passenger_price_rule: str = "average_cost",
) -> PassengerVehicleEquilibriumResult:
    network = model.case.network
    link_cost = network.free_flow_time.copy()
    price = {str(v): 0.0 for v in model.request_template["request_id"]}
    dynamic_map: dict[tuple[tuple[int, ...], int], float] = {}
    rows: list[dict[str, float | int]] = []
    final_passenger: PassengerChoiceResult | None = None
    final_vehicle: VehicleColumnGenerationResult | None = None
    final_queue: SparsePathQueueResult | None = None
    residual = np.inf

    for iteration in range(1, max_iterations + 1):
        passenger = evaluate_passenger_choice(
            model,
            link_cost,
            price,
            parameters=parameters,
            dynamic_time_override=dynamic_map if dynamic_map else None,
        )
        vehicle = solve_vehicle_service_column_generation(
            network,
            passenger.service_request_table,
            link_cost,
            **({} if vehicle_solver_options is None else dict(vehicle_solver_options)),
        )
        private_link = _private_link_flow(network, passenger.private_vehicle_path_departure)
        road_flow = private_link + vehicle.road_link_flow
        target_link_cost = bpr_cost(road_flow, network.free_flow_time, network.capacity)
        if passenger_price_rule == "dual":
            price_series = vehicle.request_dual_price
        elif passenger_price_rule == "average_cost":
            price_series = vehicle.average_service_price
        else:
            raise ValueError("passenger_price_rule must be 'dual' or 'average_cost'")
        target_price = {str(k): float(v) for k, v in price_series.items()}
        cost_residual = float(np.max(np.abs(target_link_cost - link_cost) / np.maximum(link_cost, 1.0)))
        price_residual_absolute = float(max((abs(target_price[k] - price.get(k, 0.0)) for k in target_price), default=0.0))
        price_residual = float(max((
            abs(target_price[k] - price.get(k, 0.0)) / max(abs(target_price[k]), abs(price.get(k, 0.0)), 1.0)
            for k in target_price
        ), default=0.0))
        residual = max(cost_residual, price_residual, passenger.mass_residual, vehicle.demand_residual)

        if dynamic_feedback and iteration % max(queue_every, 1) == 0:
            paths, departures = _aggregate_dynamic_paths(model, passenger, vehicle)
            queue = run_sparse_path_point_queue(
                network,
                paths,
                departures,
                dt_minutes=5.0,
                horizon_steps=queue_horizon_steps,
                capacity_multiplier=capacity_multiplier,
            )
            target_dynamic = _queue_time_map(paths, queue)
            if dynamic_map:
                keys = set(dynamic_map) | set(target_dynamic)
                dynamic_residual = max(
                    (
                        abs(target_dynamic.get(k, dynamic_map.get(k, 0.0)) - dynamic_map.get(k, target_dynamic.get(k, 0.0)))
                        / max(abs(dynamic_map.get(k, target_dynamic.get(k, 1.0))), 1.0)
                        for k in keys
                    ),
                    default=0.0,
                )
                residual = max(residual, float(dynamic_residual))
                dynamic_map = {
                    k: (1.0 - dynamic_damping) * dynamic_map.get(k, v) + dynamic_damping * v
                    for k, v in target_dynamic.items()
                }
            else:
                dynamic_map = target_dynamic
            final_queue = queue

        rows.append({
            "iteration": iteration,
            "fixed_point_residual": residual,
            "cost_residual": cost_residual,
            "service_price_residual": price_residual,
            "service_price_residual_absolute": price_residual_absolute,
            "passenger_mass_residual": passenger.mass_residual,
            "vehicle_service_shortfall": vehicle.demand_residual,
            "vehicle_pricing_gap": vehicle.relative_pricing_gap,
            "private_vehicle_trips": passenger.total_private_vehicle_trips,
            "service_vehicle_trips": float(vehicle.pattern_table["vehicle_flow"].sum()),
            "road_vehicle_flow_sum": float(road_flow.sum()),
        })
        link_cost = (1.0 - damping) * link_cost + damping * target_link_cost
        price = {
            k: (1.0 - damping) * price.get(k, 0.0) + damping * target_price.get(k, 0.0)
            for k in set(price) | set(target_price)
        }
        final_passenger, final_vehicle = passenger, vehicle
        if iteration >= 6 and residual <= tolerance:
            break

    if final_passenger is None or final_vehicle is None:
        raise RuntimeError("coupled solve did not execute")
    private_link = _private_link_flow(network, final_passenger.private_vehicle_path_departure)
    road_flow = private_link + final_vehicle.road_link_flow
    paths, departures = _aggregate_dynamic_paths(model, final_passenger, final_vehicle)
    final_queue = run_sparse_path_point_queue(
        network,
        paths,
        departures,
        dt_minutes=5.0,
        horizon_steps=queue_horizon_steps,
        capacity_multiplier=capacity_multiplier,
    )
    dynamic_map = _queue_time_map(paths, final_queue)
    return PassengerVehicleEquilibriumResult(
        model=model,
        passenger=final_passenger,
        vehicle=final_vehicle,
        road_link_vehicle_flow=road_flow,
        link_cost=link_cost,
        queue=final_queue,
        fixed_point_residual=float(residual),
        iterations=len(rows),
        history=pd.DataFrame(rows),
        dynamic_path_time=dynamic_map,
    )


# ---------------------------------------------------------------------------
# Typed coupling objects and export helpers
# ---------------------------------------------------------------------------


def build_passenger_vehicle_coupling_operators(
    model: PassengerVehicleModel,
    result: VehicleColumnGenerationResult,
) -> tuple[TypedOperator, TypedOperator]:
    """Return R(request <- passenger column) and S(request <- vehicle pattern)."""
    pattern_axis = Axis(
        "vehicle_service_pattern",
        tuple(result.pattern_table["pattern_id"].astype(str)),
        "shared-vehicle and bus service route columns",
    )
    request_id_to_pos = {str(v): i for i, v in enumerate(model.request_template["request_id"])}
    rows: list[int] = []
    cols: list[int] = []
    values: list[float] = []
    for j, row in enumerate(result.pattern_table.itertuples(index=False)):
        ids = [v for v in str(row.served_request_ids).split(";") if v]
        caps = [float(v) for v in str(row.served_capacities).split(";") if v]
        for request_id, capacity in zip(ids, caps, strict=True):
            rows.append(request_id_to_pos[request_id])
            cols.append(j)
            values.append(capacity)
    supply = sparse_operator_from_triplets(
        name="vehicle_pattern_to_service_capacity",
        source=pattern_axis,
        target=model.request_axis,
        rows=rows,
        cols=cols,
        values=values,
        input_measure="vehicle_flow",
        output_measure="person_flow",
        conservation="none",
        description="Converts vehicle-route flows to provided passenger-seat/service capacity.",
    )
    return model.column_to_request, supply


def export_passenger_vehicle_results(
    result: PassengerVehicleEquilibriumResult,
    output_dir: str | "os.PathLike[str]",
) -> None:
    from pathlib import Path
    import json

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    result.model.groups.to_csv(output / "passenger_group.csv", index=False)
    table = result.passenger.column_table.copy()
    for field in ("road_path", "private_vehicle_path", "bus_segment_path"):
        table[field] = table[field].map(lambda p: ";".join(map(str, tuple(p))))
    table.to_csv(output / "passenger_column_flow.csv", index=False)
    result.passenger.mode_share.to_csv(output / "passenger_mode_share.csv", index=False)
    result.passenger.departure_share.to_csv(output / "passenger_departure_share.csv", index=False)
    result.passenger.activity_mode_share.to_csv(output / "activity_mode_share.csv", index=False)
    request = result.passenger.service_request_table.copy()
    request["service_dual_price"] = request["request_id"].map(result.vehicle.request_dual_price).fillna(0.0)
    request["average_service_price"] = request["request_id"].map(result.vehicle.average_service_price).fillna(0.0)
    request["supplied_capacity"] = result.vehicle.supplied_capacity
    request["capacity_slack"] = request["supplied_capacity"] - request["demand"]
    request.to_csv(output / "service_request_flow.csv", index=False)
    result.vehicle.pattern_table.to_csv(output / "vehicle_route_flow.csv", index=False)

    # GMNS/TAPLite-style multimodal aliases with explicit flow measures.
    od_flow = (
        table.groupby("od_id", as_index=False)["person_flow"].sum()
        .rename(columns={"person_flow": "flow"})
    )
    od_flow["flow_measure"] = "person_flow"
    od_flow.to_csv(output / "od_flow.csv", index=False)

    route_flow = (
        table.groupby(["od_id", "mode", "departure_index", "road_path"], as_index=False)["person_flow"].sum()
        .rename(columns={"person_flow": "flow", "road_path": "link_index_sequence"})
    )
    route_flow.insert(0, "route_id", [f"passenger_route_{i}" for i in range(len(route_flow))])
    route_flow["flow_measure"] = "person_flow"
    route_flow.to_csv(output / "route_flow.csv", index=False)

    vehicle_path_rows: list[dict[str, object]] = []
    for i, ((path, departure), amount) in enumerate(sorted(result.passenger.private_vehicle_path_departure.items())):
        vehicle_path_rows.append({
            "path_id": f"private_{i}",
            "source_type": "private_passenger_column",
            "service_mode": "private_auto",
            "departure_index": int(departure),
            "link_index_sequence": ";".join(map(str, path)),
            "flow": float(amount),
            "flow_measure": "vehicle_flow",
        })
    for row in result.vehicle.pattern_table.itertuples(index=False):
        amount = float(row.vehicle_flow)
        if amount <= 1e-12:
            continue
        vehicle_path_rows.append({
            "path_id": str(row.pattern_id),
            "source_type": "service_vehicle_pattern",
            "service_mode": str(row.service_mode),
            "departure_index": int(row.departure_index),
            "link_index_sequence": str(row.link_index_sequence),
            "flow": amount,
            "flow_measure": "vehicle_flow",
        })
    vehicle_path = pd.DataFrame(vehicle_path_rows)
    vehicle_path.to_csv(output / "path_flow.csv", index=False)
    vehicle_path.to_csv(output / "vehicle_path_departure_flow.csv", index=False)
    if vehicle_path.empty:
        departure_profile = pd.DataFrame(columns=["departure_index", "vehicle_flow", "share"])
    else:
        departure_profile = vehicle_path.groupby("departure_index", as_index=False)["flow"].sum().rename(columns={"flow": "vehicle_flow"})
        departure_profile["share"] = departure_profile["vehicle_flow"] / max(float(departure_profile["vehicle_flow"].sum()), 1e-12)
    departure_profile.to_csv(output / "departure_profile.csv", index=False)

    link_table = pd.DataFrame({
        "link_id": result.model.case.network.links["link_id"].astype(str),
        "flow": result.road_link_vehicle_flow,
        "flow_measure": "vehicle_flow",
        "travel_time": result.link_cost,
        "free_flow_time": result.model.case.network.free_flow_time,
        "capacity": result.model.case.network.capacity,
    })
    link_table.to_csv(output / "link_flow.csv", index=False)

    result.vehicle.history.to_csv(output / "vehicle_column_generation_history.csv", index=False)
    result.history.to_csv(output / "passenger_vehicle_fixed_point_history.csv", index=False)
    pd.DataFrame({
        "link_id": result.model.case.network.links["link_id"].astype(str),
        "vehicle_flow": result.road_link_vehicle_flow,
        "travel_time": result.link_cost,
        "free_flow_time": result.model.case.network.free_flow_time,
        "capacity": result.model.case.network.capacity,
    }).to_csv(output / "road_link_vehicle_flow.csv", index=False)
    result.queue.history.to_csv(output / "multimodal_queue_history.csv", index=False)
    request_operator, supply_operator = build_passenger_vehicle_coupling_operators(result.model, result.vehicle)
    coupling_rows: list[dict[str, object]] = []
    request_matrix = request_operator.matrix.tocoo()
    for r, c, value in zip(request_matrix.row, request_matrix.col, request_matrix.data, strict=True):
        coupling_rows.append({
            "coupling_type": "passenger_request",
            "request_id": result.model.request_axis.labels[int(r)],
            "column_id": result.model.column_axis.labels[int(c)],
            "coefficient": float(value),
        })
    supply_matrix = supply_operator.matrix.tocoo()
    for r, c, value in zip(supply_matrix.row, supply_matrix.col, supply_matrix.data, strict=True):
        coupling_rows.append({
            "coupling_type": "vehicle_capacity",
            "request_id": result.model.request_axis.labels[int(r)],
            "column_id": supply_operator.source.labels[int(c)],
            "coefficient": float(value),
        })
    pd.DataFrame(coupling_rows).to_csv(output / "passenger_vehicle_coupling.csv", index=False)
    manifest = {
        "framework": "STB-FTT passenger-vehicle multimodal extension",
        "certificate": "passenger mass + vehicle service feasibility + enumerated vehicle pricing + queue conservation",
        "fixed_point_residual": result.fixed_point_residual,
        "passenger_mass_residual": result.passenger.mass_residual,
        "vehicle_service_shortfall": result.vehicle.demand_residual,
        "vehicle_pricing_gap": result.vehicle.relative_pricing_gap,
        "queue_conservation_residual": float(np.max(np.abs(result.queue.conservation_residual))),
        "spillback": False,
    }
    (output / "passenger_vehicle_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
