"""E4/F1-F2(lite): TRMG2 regional transfer validation + certified
assignment. Full validation on the complete AM bundle; certified
full-space-priced assignment on the top-N OD subset (coverage
reported), full-1M-OD run staged next."""
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
from tensormobility.adapters.trmg2 import load_trmg2
from tensormobility.dta.sparse_assignment import (network_from_case,
                                                  solve_fw)

OUT = Path(__file__).parent / 'outputs' / 'trmg2'
OUT.mkdir(parents=True, exist_ok=True)
TOP = 300_000

full = load_trmg2('AM')
(OUT / 'f1_validation.json').write_text(
    json.dumps(full.extras['validation'], indent=1), encoding='utf-8')
vol = np.sort(full.demand.volume.to_numpy())[::-1]
coverage = float(vol[:TOP].sum() / vol.sum())

case = load_trmg2('AM', top_od=TOP)
net = network_from_case(case)
t0 = time.perf_counter()
r = solve_fw(net, max_rounds=14, tolerance=1e-4)
wall = time.perf_counter() - t0
r.history.to_csv(OUT / 'f2_certified_fw_history.csv', index=False)

lines = ['# TRMG2 E4 (F1-F2 lite) — verified results\n',
         'Generated by `python cases/run_trmg2_f1.py`. Single-process, '
         'single-thread.\n',
         '## F1 transfer validation (full AM bundle)\n',
         '```json\n' + json.dumps(full.extras['validation'], indent=1)
         + '\n```\n',
         '## F2-lite certified assignment '
         f'(top {TOP:,} ODs = {100*coverage:.1f}% of AM volume)\n',
         f'- full-space relative gap {r.relative_gap:.3e} in '
         f'{r.pricing_rounds} pricing rounds, {wall:.0f}s wall',
         f'- columns generated {r.n_columns:,}; active '
         f'{r.active_columns:,}; feasibility '
         f'{r.feasibility_residual:.1e}',
         '',
         'Full 1,039,117-OD assignment is the staged next step '
         '(memory-profiled column pool required).']
(OUT / 'RESULTS.md').write_text('\n'.join(lines), encoding='utf-8')
print('\n'.join(lines))
