"""MAGE mixed-autonomy ride-hailing profile — grid demonstration cases.

Base two-company equilibrium + three policy sweeps (AV cap, fleet size,
patience), every point carrying the full certificate set."""
from pathlib import Path

import numpy as np
import pandas as pd

from tensormobility.core.unified_networks import load_case
from tensormobility.profiles.mage_profile import (solve_mage, default_two_company_config,
                                  multi_start_spread, Company)

OUT = Path(__file__).parent / 'outputs' / 'mage_grid'
OUT.mkdir(parents=True, exist_ok=True)


def certline(r):
    return (f'fp {r["fixed_point_residual"]:.1e}, '
            f'fw {r["assignment_gap"]:.1e}, '
            f'cons {r["conservation_residual"]:.1e}, '
            f'patience {r["patience_violation"]:.1e}, '
            f'compl {r["rationing_complementarity_violation"]:.1e}, '
            f'fleet {r["fleet_feasibility_violation"]:.1e}')


def main():
    case = load_case('grid', rows=8, columns=8, n_od=12,
                     demand_per_od=400.0, base_capacity=900.0)
    lines = ['# MAGE profile on the 8x8 grid — verified results\n',
             'Generated by `python run_mage_grid.py`. Steady-state '
             'mixed-autonomy ride-hailing equilibrium (TRB-D-26-00426 '
             'operator profile): 2 TNCs x {AV, HV} + solo, patience-'
             'capped matching queue (distinct from the road queue), '
             'certified road assignment each outer iteration.\n']

    base = solve_mage(case, default_two_company_config())
    ms = multi_start_spread(case, default_two_company_config())
    lines += ['## Base equilibrium\n',
              f'- converged in {base["outer_iterations"]} outer '
              f'iterations; certificates: {certline(base)}',
              f'- multi-start share spread (2 seeds): '
              f'{ms["spread"]:.2e} (GNE uniqueness not assumed)',
              f'- mode shares: ' + ', '.join(
                  f'{k} {100*v:.1f}%'
                  for k, v in base['mode_share'].items()),
              f'- matching waits (min): ' + ', '.join(
                  f'{k} {v:.2f}' for k, v in base['w_match'].items()),
              f'- served fraction {base["served_fraction"]:.3f}\n']

    # AV-cap sweep (company alpha)
    rows = []
    for cap in (0.0, 0.25, 0.5, 0.75, 1.0):
        cfg = default_two_company_config()
        cfg.companies[0] = Company('alpha', fleet=400.0, av_cap=cap,
                                   fare_equiv_min={'AV': 6.0, 'HV': 9.0},
                                   op_cost_equiv_min={'AV': 3.0,
                                                      'HV': 7.0})
        r = solve_mage(case, cfg)
        rows.append(dict(av_cap=cap,
                         alpha_av=r['mode_share']['alpha:AV'],
                         alpha_hv=r['mode_share']['alpha:HV'],
                         solo=r['mode_share']['solo'],
                         w_alpha_av=r['w_match']['alpha:AV'],
                         served=r['served_fraction']))
    df = pd.DataFrame(rows)
    df.to_csv(OUT / 'av_cap_sweep.csv', index=False)
    lines += ['## AV-cap sweep (company alpha)\n',
              '| AV cap | alpha:AV share | alpha:HV share | solo | '
              'alpha:AV wait | served |', '|---:|---:|---:|---:|---:|---:|']
    for r_ in rows:
        lines.append(f'| {r_["av_cap"]:.2f} | {100*r_["alpha_av"]:.1f}% '
                     f'| {100*r_["alpha_hv"]:.1f}% | '
                     f'{100*r_["solo"]:.1f}% | {r_["w_alpha_av"]:.2f} | '
                     f'{100*r_["served"]:.1f}% |')
    lines.append('')

    # fleet-size sweep
    rows = []
    for scale in (0.3, 0.6, 1.0, 1.5):
        cfg = default_two_company_config()
        for c in cfg.companies:
            c.fleet *= scale
        r = solve_mage(case, cfg)
        rows.append(dict(fleet_scale=scale,
                         max_wait=max(r['w_match'].values()),
                         served=r['served_fraction'],
                         solo=r['mode_share']['solo']))
    pd.DataFrame(rows).to_csv(OUT / 'fleet_sweep.csv', index=False)
    lines += ['## Fleet-size sweep ("how many vehicles", equilibrium '
              'version)\n',
              '| fleet scale | max wait (min) | served | solo share |',
              '|---:|---:|---:|---:|']
    for r_ in rows:
        lines.append(f'| {r_["fleet_scale"]:.1f} | {r_["max_wait"]:.2f} '
                     f'| {100*r_["served"]:.1f}% | '
                     f'{100*r_["solo"]:.1f}% |')
    lines.append('')

    # patience sweep
    rows = []
    for pat in (4.0, 8.0, 12.0, 20.0):
        cfg = default_two_company_config()
        cfg.patience_min = pat
        r = solve_mage(case, cfg)
        rh = 1.0 - r['mode_share']['solo']
        rows.append(dict(patience=pat, rh_share=rh,
                         served=r['served_fraction'],
                         max_wait=max(r['w_match'].values())))
    pd.DataFrame(rows).to_csv(OUT / 'patience_sweep.csv', index=False)
    lines += ['## Customer-patience sweep\n',
              '| patience (min) | ride-hailing share | served | '
              'max wait |', '|---:|---:|---:|---:|']
    for r_ in rows:
        lines.append(f'| {r_["patience"]:.0f} | '
                     f'{100*r_["rh_share"]:.1f}% | '
                     f'{100*r_["served"]:.1f}% | {r_["max_wait"]:.2f} |')
    lines += ['',
              '## Interpretation limits\n',
              '- Steady-state diagonalized best response with an exact '
              'Newton solve of the stiff choice/wait subsystem; the '
              'full MAGE NCP/VI (GAMS/PATH class) is the declared v0.6 '
              'solver extension, and existence for the dynamic version '
              'is NOT claimed (the paper proves it for its continuous '
              'steady-state operators).',
              '- Pickup stage enters as deadhead VMT factor + access '
              'time, not yet as routed pickup paths from vehicle '
              'locations.',
              '- Company fleet response is demand-tracking with AV-'
              'first priority under the cap, not full profit '
              'maximization.']
    (OUT / 'RESULTS.md').write_text('\n'.join(lines), encoding='utf-8')
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
